version: '3'

services:
  server:
    image: node:14
    working_dir: /app
    volumes: 
      - ./server:/app
    ports:
      - 3000:3000
    command: yarn start
  
  front:
    image: node:14
    working_dir: /app
    volumes:
        - ./front:/app
    ports:
        - 3333:3000
    command: yarn start

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - front

  db:
    image: mysql:5.7
    ports:
        - 3306:3306
    environment:
        TZ: 'Asia/Tokyo'
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - ./docker/db/cnf:/etc/mysql/conf.d
        - ./docker/db:/docker-entrypoint-initdb.d
        - ./db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=docker
    links:
      - db
    ports:
        - 8080:80